name: 自动更新数据

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 1 点执行
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: 运行爬虫脚本
        run: python scripts/fetch_data.py

      - name: 提交并推送更新
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/historical_persons.json data/news.json
          git commit -m "自动更新历史人物和时事新闻数据" || echo "无变化"
          git push
