name: 自动更新历史人物和时事新闻数据

on:
  schedule:
    - cron: '0 2 * * *'  # 每天UTC 2点 (北京时间10点) 运行
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: 运行爬虫脚本更新JSON
        run: python scripts/fetch_data.py

      - name: 提交并推送更改
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/historical_persons.json data/news.json
          git diff --quiet || (git commit -m "自动更新历史人物和时事新闻数据" && git push)
